// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_service.Data;

#nullable disable

namespace api_service.Migrations
{
    [DbContext(typeof(BlogDatabase))]
    [Migration("20251211112951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_service.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Alice",
                            Content = "React is a JavaScript library for building user interfaces.",
                            CreatedAt = new DateTime(2025, 11, 21, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7824),
                            Title = "Introduction to React"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Bob",
                            Content = "Learn the basics of .NET Core development.",
                            CreatedAt = new DateTime(2025, 11, 22, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7915),
                            Title = "Getting started with .NET Core"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Charlie",
                            Content = "EF Core allows you to work with databases using .NET objects.",
                            CreatedAt = new DateTime(2025, 11, 23, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7921),
                            Title = "Understanding Entity Framework Core"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Diana",
                            Content = "Learn about let, const, arrow functions, and more.",
                            CreatedAt = new DateTime(2025, 11, 24, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7926),
                            Title = "JavaScript ES6 Features"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Eve",
                            Content = "Manage asynchronous operations easily in C#.",
                            CreatedAt = new DateTime(2025, 11, 25, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7932),
                            Title = "C# Async & Await"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Frank",
                            Content = "Best practices for designing RESTful APIs.",
                            CreatedAt = new DateTime(2025, 11, 26, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7937),
                            Title = "REST API Design"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Grace",
                            Content = "Query your collections efficiently using LINQ.",
                            CreatedAt = new DateTime(2025, 11, 27, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7942),
                            Title = "Understanding LINQ"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Hank",
                            Content = "Learn how DI improves code modularity.",
                            CreatedAt = new DateTime(2025, 11, 28, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7948),
                            Title = "Dependency Injection in ASP.NET Core"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Ivy",
                            Content = "UseState, UseEffect, and custom hooks explained.",
                            CreatedAt = new DateTime(2025, 11, 29, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7953),
                            Title = "React Hooks Overview"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Jack",
                            Content = "Write tests for your .NET Core applications.",
                            CreatedAt = new DateTime(2025, 11, 30, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7958),
                            Title = "Unit Testing with xUnit"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Alice",
                            Content = "Implement client-side routing with React Router.",
                            CreatedAt = new DateTime(2025, 12, 1, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7963),
                            Title = "Routing in React"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Bob",
                            Content = "How to create and configure middleware in your app.",
                            CreatedAt = new DateTime(2025, 12, 2, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7968),
                            Title = "Middleware in ASP.NET Core"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Charlie",
                            Content = "Learn how to manage state with Redux or Context API.",
                            CreatedAt = new DateTime(2025, 12, 3, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7973),
                            Title = "State Management in React"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Diana",
                            Content = "Basic operations with SQL Server using EF Core.",
                            CreatedAt = new DateTime(2025, 12, 4, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7978),
                            Title = "Working with SQL Server"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Eve",
                            Content = "Compare Blazor and React for frontend development.",
                            CreatedAt = new DateTime(2025, 12, 5, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7983),
                            Title = "Blazor vs React"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Frank",
                            Content = "Implement authentication with Identity.",
                            CreatedAt = new DateTime(2025, 12, 6, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7988),
                            Title = "Authentication in ASP.NET Core"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Grace",
                            Content = "Controlled vs uncontrolled components in forms.",
                            CreatedAt = new DateTime(2025, 12, 7, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7992),
                            Title = "Forms in React"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Hank",
                            Content = "Learn built-in logging providers and how to use them.",
                            CreatedAt = new DateTime(2025, 12, 8, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(7997),
                            Title = "Logging in .NET Core"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Ivy",
                            Content = "Use error boundaries to handle React component errors.",
                            CreatedAt = new DateTime(2025, 12, 9, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(8002),
                            Title = "Error Handling in React"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Jack",
                            Content = "Deployment strategies for ASP.NET Core applications.",
                            CreatedAt = new DateTime(2025, 12, 10, 15, 29, 51, 74, DateTimeKind.Local).AddTicks(8007),
                            Title = "Deploying ASP.NET Core Apps"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
