// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_service.Data;

#nullable disable

namespace api_service.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20251210101308_insertData")]
    partial class insertData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_service.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Informatique",
                            Description = "Ordinateur portable performant avec processeur i7",
                            ImageUrl = "https://example.com/images/laptop-lenovo.jpg",
                            Name = "Laptop Lenovo",
                            Price = 1200.50m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Téléphonie",
                            Description = "Smartphone haut de gamme avec écran AMOLED",
                            ImageUrl = "https://example.com/images/samsung-s24.jpg",
                            Name = "Smartphone Samsung S24",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Audio",
                            Description = "Casque Bluetooth à réduction de bruit",
                            ImageUrl = "https://example.com/images/sony-wh1000xm5.jpg",
                            Name = "Casque Sony WH-1000XM5",
                            Price = 349.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Informatique",
                            Description = "Clavier RGB pour gaming",
                            ImageUrl = "https://example.com/images/logitech-keyboard.jpg",
                            Name = "Clavier mécanique Logitech",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Informatique",
                            Description = "Souris gamer ergonomique avec 11 boutons programmables",
                            ImageUrl = "https://example.com/images/razer-basilisk.jpg",
                            Name = "Souris Razer Basilisk",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Informatique",
                            Description = "Moniteur 4K UHD IPS",
                            ImageUrl = "https://example.com/images/dell-monitor.jpg",
                            Name = "Écran Dell 27 pouces",
                            Price = 499.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Informatique",
                            Description = "Imprimante tout-en-un sans fil",
                            ImageUrl = "https://example.com/images/hp-deskjet.jpg",
                            Name = "Imprimante HP DeskJet 4155e",
                            Price = 149.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Informatique",
                            Description = "Stockage rapide NVMe M.2",
                            ImageUrl = "https://example.com/images/samsung-ssd.jpg",
                            Name = "Disque SSD Samsung 1TB",
                            Price = 129.50m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Informatique",
                            Description = "Caméra HD 1080p pour visioconférence",
                            ImageUrl = "https://example.com/images/logitech-c920.jpg",
                            Name = "Webcam Logitech C920",
                            Price = 89.00m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Mobilier",
                            Description = "Chaise de bureau premium pour le confort",
                            ImageUrl = "https://example.com/images/secretlab-chair.jpg",
                            Name = "Chaise ergonomique Secretlab",
                            Price = 459.99m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Gaming",
                            Description = "Casque réalité virtuelle autonome",
                            ImageUrl = "https://example.com/images/oculus-quest2.jpg",
                            Name = "Casque VR Oculus Quest 2",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Informatique",
                            Description = "Tablette légère et performante",
                            ImageUrl = "https://example.com/images/ipad-air.jpg",
                            Name = "Tablette Apple iPad Air",
                            Price = 599.00m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Wearable",
                            Description = "Montre connectée multisport",
                            ImageUrl = "https://example.com/images/garmin-fenix7.jpg",
                            Name = "Smartwatch Garmin Fenix 7",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Audio",
                            Description = "Enceinte portable Bluetooth",
                            ImageUrl = "https://example.com/images/bose-soundlink.jpg",
                            Name = "Haut-parleur Bose SoundLink",
                            Price = 199.00m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Réseau",
                            Description = "Routeur WiFi 6 ultra-rapide",
                            ImageUrl = "https://example.com/images/asus-router.jpg",
                            Name = "Router WiFi ASUS RT-AX88U",
                            Price = 299.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
